version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: coredesk-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: coredeskdb
    ports:
      - "5432:5432"
    volumes:
      - coredesk_postgres_data:/var/lib/postgresql/data

volumes:
  coredesk_postgres_data: